### ISSUE TITLE
Read raddins.csv from github?

### ISSUE THREAD

**Issue by calligross** [csgillespie/addinmanager#1]
Hi,

your add-in manager is a great idea, but have you considered reading raddins.csv from github via http?

Regards
Calli

**Comment by csgillespie** [comment]
That was in the back of my mind. What about 
1. Try and read `raddins.csv`
2. Fall back to local copy

---

It just dawned on me that read.csv works with URLs, so it's a trivial change!

**Comment by calligross** [comment]
That's what I thought as ideal solution. :-)
