### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by IeUDE** [csgillespie/addinmanager#2]
After installation and upon launching the addin manager through the menu, i get the following error:

```
> addinmanager:::addin_manager()
Error in tag("h1", list(...)) : could not find function "a"
```

**Comment by csgillespie** [comment]
Fixed by https://github.com/csgillespie/addinmanager/commit/bcd33390e38cc7df84589b9a0797999c441a3b67 

Thanks

**Comment by IeUDE** [comment]
Thank you, worked after i re-run:

```
devtools::install_github('rstudio/DT', force = TRUE)
devtools::install_github("csgillespie/addinmanager", force = TRUE)
```

and restarted RStudio
